language: python
sudo: false

addons:
  apt:
    packages:
      - rpm

python:
  #- 2.7
  #- 3.4
  - 3.5
  - 3.6

install:
    - bash ci/install.sh

script:
    - bash ci/script.sh

before_deploy:
    - bash ci/before_deploy.sh

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: mre0
  password: $PYPI_PASSWORD
  on:
    tags: true
    python: '3.6'