[package]
name = "hyperjson"
version = "0.1.0"
authors = ["Matthias Endler <matthias-endler@gmx.net>"]

[dependencies]
serde_json = "1.0.13"
version = "3.0.0"
failure = "0.1.1"
serde = "1.0.53"
serde_derive = "1.0.53"

[dependencies.pyo3]
version = "0.2.6"
default-features = false

[lib]
crate-type = ["cdylib"]
name = "hyperjson"
